### PR TITLE
Added comment verification. Fixed incorrect comments.

### PR DESCRIPTION
**Pull request by pirat9600q**
This comment adds comment verification for IndentationCheck input files. It also contains chages in input files.

### CODE REVIEW

**Comment by romani** [comment]
Results :

Tests in error: 
  correctForTest(com.google.checkstyle.test.chapter4formatting.rule4841indentation.IndentationTest): File "/home/rivanov/java/git-others/checkstyle/google-style-config-test/src/main/java/com/google/checkstyle/test/chapter4formatting/rule452indentcontinuationlines/IndentationCorrectForAndParameterInput.java" has no indentation comment or its format malformed. Error on line: 1
  correctClassTest(com.google.checkstyle.test.chapter4formatting.rule4841indentation.IndentationTest): File "/home/rivanov/java/git-others/checkstyle/google-style-config-test/src/main/java/com/google/checkstyle/test/chapter4formatting/rule452indentcontinuationlines/IndentationCorrectClassInput.java" has no indentation comment or its format malformed. Error on line: 1
  correctIfTest(com.google.checkstyle.test.chapter4formatting.rule4841indentation.IndentationTest): File "/home/rivanov/java/git-others/checkstyle/google-style-config-test/src/main/java/com/google/checkstyle/test/chapter4formatting/rule452indentcontinuationlines/IndentationCorrectIfAndParameterInput.java" has no indentation comment or its format malformed. Error on line: 1
  correctReturnTest(com.google.checkstyle.test.chapter4formatting.rule4841indentation.IndentationTest): File "/home/rivanov/java/git-others/checkstyle/google-style-config-test/src/main/java/com/google/checkstyle/test/chapter4formatting/rule452indentcontinuationlines/IndentationCorrectReturnAndParameterInput.java" has no indentation comment or its format malformed. Error on line: 1
  correctFieldTest(com.google.checkstyle.test.chapter4formatting.rule4841indentation.IndentationTest): File "/home/rivanov/java/git-others/checkstyle/google-style-config-test/src/main/java/com/google/checkstyle/test/chapter4formatting/rule452indentcontinuationlines/IndentationCorrectFieldAndParameterInput.java" has no indentation comment or its format malformed. Error on line: 1
  correctWhileTest(com.google.checkstyle.test.chapter4formatting.rule4841indentation.IndentationTest): File "/home/rivanov/java/git-others/checkstyle/google-style-config-test/src/main/java/com/google/checkstyle/test/chapter4formatting/rule452indentcontinuationlines/IndentationCorrectWhileDoWhileAndParameterInput.java" has no indentation comment or its format malformed. Error on line: 1
  correctTest(com.google.checkstyle.test.chapter4formatting.rule4841indentation.IndentationTest): File "/home/rivanov/java/git-others/checkstyle/google-style-config-test/src/main/java/com/google/checkstyle/test/chapter4formatting/rule452indentcontinuationlines/IndentationCorrectInput.java" has no indentation comment or its format malformed. Error on line: 1

Tests run: 87, Failures: 0, Errors: 7, Skipped: 0

**Comment by romani** [comment]
https://travis-ci.org/checkstyle/google-style-config-test/jobs/52868125#L2192

please do "mvn clean test" on local PC before PR

**Comment by pirat9600q** [comment]
I executed tests with "mvn clean test" on local PC before PR and tests passed successfully. I cant reproduce problem on my PC.

**Comment by romani** [comment]
recheck that your use latest sources and do all as Travis do to run UTs - https://github.com/checkstyle/google-style-config-test/blob/master/.travis.yml#L8

, not all java versions are affected - https://travis-ci.org/checkstyle/google-style-config-test/builds/52868123
I used java8.

**Comment by pirat9600q** [comment]
Tryed to run "mvn clean install -Passembly" in checkstyle folder (as Travis do) prior to runnig "mvn clean test" in google-style-config-test folder. Nothing changed. Test passed successfully. I am using OracleJDK 8(which fails on Travis system).

**Comment by romani** [comment]
please use the same java version , we can not keep Travis as failed, the whole quality is based on it.

I tried on my java7, the same failure result :
```
~/java/google-style-config-test [master ↑·1|… 1] 
$ java -version
java version "1.7.0_75"
Java(TM) SE Runtime Environment (build 1.7.0_75-b13)
Java HotSpot(TM) 64-Bit Server VM (build 24.75-b04, mixed mode)
```

**Pull request merged**
