### PR TITLE
Empty catch block, added UT

### PR DESCRIPTION
**Pull request by alexkravin**
Added UTs for Empty Catch Block Check

As this project gets google_checks.xml from main repo - it will be needed update config firstly and then update UTs, right now travis will fail build

### CODE REVIEW

**Comment by romani** [comment]
1) build is failed.

2) I do not understand why you introduced changes at .gitignore and google_checks.xml

3) please make 3 Input files:
- no violations
- violations by comment
- violations by name of variable

**Comment by alexkravin** [comment]
1) Yes, ok

2) It was for my testing and to show you which values I have tested, now UTs test EmptyCatchBlockCheck with default values, removed changes to .gitignore and google_checks.xml

3) added 
- no violations
-violations by comment
and corresponding UTs
but I think there's no need to make input 
```
violations by variable name
```
as it has no value by default, it makes sense only if we will use some specific value in frames of this project.

**Comment by romani** [comment]
I do not see a reason why you change EmptyBlockInputCatch.java , most of input cases are valid not matter what implementation Check have.
that is even good for test to be completely independent to Check implementation.

Please keep unchanged old input cases as  much as possible .

**Comment by alexkravin** [comment]
Old inputs are unchanged now.

**Comment by alexkravin** [comment]
Extended UT inputs

**Comment by alexkravin** [comment]
Added variable name UT and corresponding input according to google_checks.xml config

**Comment by romani** [comment]
> newCheckConfig.addAttribute("exceptionVariableName", "expected");

In that project, there should be no changes to configuration , configuration is tested as is, in all inputs "//warn" should be at places where it will be in real usage of google_checks.xml

**Comment by alexkravin** [comment]
Done

**Comment by romani** [comment]
merged as FF

**Pull request closed without merging**
